CREATE TABLE ANALISE_E_AUDITORIA_BACA (

    idAssociaBaca             NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_ASSOCIABACA NOT NULL PRIMARY KEY,
    data                      DATE NOT NULL,
    descricao                 VARCHAR2(255),
    idAnaliseBaca_fk          INT NOT NULL,
    idAuditorBaca_fk          INT NOT NULL,
    
    -- CONSTRAINTS E CHAVES ESTRANGEIRAS
    CONSTRAINT CHK_ANALISEBACA_FK FOREIGN KEY (idAnaliseBaca_fk) REFERENCES BACALHAU_ANALISE (idAnaliseBaca),
    CONSTRAINT CHK_AUDITORBACA_FK FOREIGN KEY (idAuditorBaca_fk) REFERENCES AUDITORIA_BACA (idAudi_bacalhau)

) TABLESPACE TBS_AUDITORIA_BACA;