CREATE TABLE DEVOLUCAO_BACALHAU (

    idDevolucaoBaca         NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_DEVOLUCAO_BACA NOT NULL PRIMARY KEY,
    descricao               VARCHAR2(255) NOT NULL,
    idAnaliseBaca           INT NOT NULL,
    
    
    -- CONSTRAINT E CHAVES ESTRANGEIRAS
    CONSTRAINT CHK_FK_ANALISEBACA FOREIGN KEY (idAnaliseBaca) REFERENCES BACALHAU_ANALISE (idAnaliseBaca)

)TABLESPACE TBS_DEVOLUCAO_BACALHAU;