-- TABLESPACE FORNECEDOR
CREATE TABLESPACE TBS_FORNECEDOR
DATAFILE 'C:\Users\dudu\Desktop\projetos\QualidadeBD\Arquivos\TABLESPACES\oradata_fornecedor\fornecedor.dbf' SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 256M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M;

-- TABLESPACE FILIAL
CREATE TABLESPACE TBS_FILIAL
DATAFILE 'C:\Users\dudu\Desktop\projetos\QualidadeBD\Arquivos\TABLESPACES\oradata_filial\filial.dbf' SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 256M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M;

--TABLESPACE CATEGORIA
CREATE TABLESPACE TBS_CATEGORIA
DATAFILE 'C:\Users\dudu\Desktop\projetos\QualidadeBD\Arquivos\TABLESPACES\oradata_categoria\categoria.dbf' SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 200M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M;

