CREATE TABLESPACE TBS_ARMAZENAMENTO_BACA
DATAFILE '/u01/app/oracle/oradata/ORCL/datafile/tbs_armazenamentoBaca.dbf' SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE UNLIMITED

EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M;