CREATE TABLESPACE TBS_ANALISE_BACALHAU
DATAFILE '/u01/app/oracle/oradata/ORCL/datafile/analiseBacalhau.dbf' SIZE 70M
AUTOEXTEND ON
NEXT 10
MAXSIZE UNLIMITED

EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M; 