CREATE TABLESPACE TBS_RECEBIMENTO_BACA
DATAFILE '/u01/app/oracle/oradata/ORCL/datafile/recebimentoBacalhau.dbf' SIZE 20M
AUTOEXTEND ON
NEXT 5M
MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M; 