CREATE TABLESPACE TBS_DEVOLUCAO_BACALHAU
DATAFILE '/u01/app/oracle/oradata/ORCL/datafile/tbs_devolucao_baca.dbf' SIZE 50M
AUTOEXTEND ON
NEXT 10
MAXSIZE UNLIMITED

EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M;